[project]
name = "fff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "basedpyright>=1.17.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
